#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100.
#Requirements:
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number
#In a list format

n=1

while [ $n -le 100 ]

do
    leftover1=$(( n % 3 ))
    leftover2=$(( n % 5 ))

   if [ "$leftover1" -eq 0 ] && [ "$leftover2" -eq 0 ]
   then
 
   echo "FizzBuzz"
   n=$(( n + 1 ))

   elif [ "$leftover1" -eq 0 ]
   then

   echo "Fizz"
   n=$(( n + 1 ))

   elif [ "$leftover2" -eq 0 ]
   then

   echo "Buzz"
   n=$(( n + 1 ))

  else
  
   echo "$n"
   n=$(( n + 1 ))

fi

done      
