#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

counter=1
while [ $counter -lt 10 ]
do
	if test $counter -eq 9
	then
		echo "Hi"
	fi

	echo "Best School"

	counter=$(( counter+1 ))
done
