#!/usr/bin/env bash
#Write Bash (init) script 11-manage_my_process that manages manage_my_process. (both files need to be pushed to git)

if [ "${1}" == "start" ]
then

 ./manage_my_process  & 
 touch -type -f /var/run/my_process.pid
 echo  "$!" > /var/run/my_process.pid  
 echo "manage_my_process started" 

elif [ "${1}" == "stop" ]
then

 kill -KILL  "$( pgrep -f manage_my_process )"
 rm /var/run/my_process.pid
 echo "manage_my_process stopped"

elif [ "${1}" == "restart" ]
then

 kill -KILL "$( pgrep -f  manage_my_process )"
 rm /var/run/my_process.pid &
 ./11-/var/run/my_process.pid
 touch -type -f  /var/run/my_process.pid
 echo "$!" >> /var/run/my_process.pid
 echo "manage_my_process restarted" 

else 

echo "Usage: manage_my_process {start|stop|restart}"
 
fi
