#!/usr/bin/env bash
#Write Bash (init) script 11-manage_my_process that manages manage_my_process. (both files need to be pushed to git)

while true 
do
 echo "I am alive!" /tmp/my_process

if { $N == "start" }

 sudo touch /var/run/my_process.pid | ./10-manage_my_process restarted | echo "manage_my_process started"

elif { $N == "stop" }

 sudo rm -type -f /var/run/my_process.pid | echo "manage_my_process stopped"

elif { $N == "restart" }

 sudo kill manage_my_process | rm -type -f /var/run/my_process.pid | ./11-manage_my_process | touch /var/run/my_process.pid | echo "manage_my_process restarted"

else 

 echo "Usage: manage_my_process {start|stop|restart}"

done
