#!/usr/bin/env bash
#Write Bash (init) script 11-manage_my_process that manages manage_my_process. (both files need to be pushed to git)

if [ "${1}" == "start" ]
then

 etc/init.d/manage_my_process start & 
 touch -type -f /var/run/my_process.pid
 echo  $$ >> /var/run/my_process.pid & 
 echo "manage_my_process started" 

elif [ "${1}" == "stop" ]
then

kill  ( cat etc/init.d/manage_my_process ) stop  &
 rm -type -f /var/run/my_process.pid  
 echo "manage_my_process stopped"

elif [ "${1}" == "restart" ]
then

kill ( cat etc/init.d/manage_my_process ) restart &
 rm -type -f /var/run/my_process.pid
 ./11-/var/run/my_process.pid &
 touch -type -f  /var/run/my_process.pid
 echo "manage_my_process restarted" 

else 

 echo "Usage: manage_my_process {start|stop|restart}"
 
fi
